-- Part 1: Create mapping table and insert all title-to-role mappings
-- Run this first in SQL Editor, then run Part 2 at the bottom

CREATE TEMP TABLE title_to_role (title text, role_name text, confidence numeric);

INSERT INTO title_to_role VALUES
-- Software Engineer variants
('Senior Developer','Software Engineer',0.9),('Developer','Software Engineer',0.7),('Software Engineer II','Software Engineer',0.9),('Software Engineer III','Software Engineer',0.9),('Lead Software Engineer','Software Engineer',0.9),('Principal Software Engineer','Software Engineer',0.9),('Senior Engineer','Software Engineer',0.7),('Lead Engineer','Software Engineer',0.7),('Principal Engineer','Software Engineer',0.7),('Staff Software Engineer','Software Engineer',0.9),('Staff Engineer','Software Engineer',0.7),('Associate Software Engineer','Software Engineer',0.9),('Full Stack Engineer','Software Engineer',0.9),('Full Stack Software Engineer','Software Engineer',0.9),('Full Stack Software Developer','Software Engineer',0.9),('Full-Stack Developer','Software Engineer',0.9),('Senior Full Stack Engineer','Software Engineer',0.9),('Software Development Engineer','Software Engineer',0.9),('Senior Software Development Engineer','Software Engineer',0.9),('Software Engineering Manager','Software Engineer',0.7),('Software Development Manager','Software Engineer',0.7),('Software Engineering Intern','Software Engineer',0.7),('Software Engineer Intern','Software Engineer',0.7),('Embedded Software Engineer','Software Engineer',0.9),('Senior Embedded Software Engineer','Software Engineer',0.9),('Embedded Engineer','Software Engineer',0.7),('Software Architect','Software Engineer',0.9),('Senior Software Architect','Software Engineer',0.9),('Application Developer','Software Engineer',0.9),('Senior Application Developer','Software Engineer',0.9),('Sr. Application Developer','Software Engineer',0.9),('Sr. Software Developer','Software Engineer',0.9),('Sr. Developer','Software Engineer',0.7),('Sr Software Developer','Software Engineer',0.9),('Software Consultant','Software Engineer',0.7),('Software Quality Engineer','Software Engineer',0.7),('Software Quality Assurance Engineer','Software Engineer',0.7),('Full Stack Python Developer','Software Engineer',0.9),('Software Development Engineer in Test (SDET)','Software Engineer',0.7),('Lead Software Developer','Software Engineer',0.9),('Senior Staff Engineer','Software Engineer',0.9),('Sr. Engineer','Software Engineer',0.7),('Senior Full Stack Developer','Software Engineer',0.9),('Sr Full Stack Developer','Software Engineer',0.9),('Senior Full Stack Java Developer','Software Engineer',0.9),('Full Stack Software Engineer','Software Engineer',0.9),('Firmware Engineer','Software Engineer',0.7),('C++ Developer','Software Engineer',0.9),('Golang Developer','Software Engineer',0.9),('Backend Developer','Software Engineer',0.9),('Solutions Engineer','Software Engineer',0.7),
-- Java Developer variants
('J2EE Developer','Java Developer',0.9),('Sr Java Full Stack Developer','Java Developer',0.9),('Sr Full Stack Java Developer','Java Developer',0.9),('Sr Java Developer','Java Developer',0.9),('Sr.Java Developer','Java Developer',0.9),('Java Backend Developer','Java Developer',0.9),('Java Architect','Java Developer',0.9),('Full-Stack Java Developer','Java Developer',0.9),('Java Fullstack Developer','Java Developer',0.9),('Senior Java/J2EE Developer','Java Developer',0.9),('Sr. Java Backend Developer','Java Developer',0.9),('Sr. Java/J2EE Full Stack Developer','Java Developer',0.9),('Big Data Developer','Java Developer',0.7),('Sr. Java/J2EE Developer','Java Developer',0.9),('Lead Java Developer','Java Developer',0.9),
-- .NET Developer variants
('Sr .Net Developer','.NET Developer',0.9),('Sr .NET Developer','.NET Developer',0.9),('Sr.Net Developer','.NET Developer',0.9),('Full Stack .Net Developer','.NET Developer',0.9),('Sr .Net Full Stack Developer','.NET Developer',0.9),('.Net Full Stack Developer','.NET Developer',0.9),('Sr. Full Stack .Net Developer','.NET Developer',0.9),('Sr. Dot Net Developer','.NET Developer',0.9),('Dot Net Developer','.NET Developer',0.9),('Lead .Net Developer','.NET Developer',0.9),
-- DevOps variants
('Sr DevOps Engineer','DevOps Engineer',0.9),('DevOps/Cloud Engineer','DevOps Engineer',0.9),('Cloud/DevOps Engineer','DevOps Engineer',0.9),('DevOps/AWS Engineer','DevOps Engineer',0.9),('Sr. AWS DevOps Engineer','DevOps Engineer',0.9),('Sr. Cloud/DevOps Engineer','DevOps Engineer',0.9),('Sr. DevOps/Cloud Engineer','DevOps Engineer',0.9),('Sr. Cloud DevOps Engineer','DevOps Engineer',0.9),('Lead DevOps Engineer','DevOps Engineer',0.9),('DevOps Architect','DevOps Engineer',0.9),('DevOps Cloud Engineer','DevOps Engineer',0.9),('Sr. DevOps/AWS Engineer','DevOps Engineer',0.9),('Sr. AWS/DevOps Engineer','DevOps Engineer',0.9),('DevSecOps Engineer','DevOps Engineer',0.9),('Sr. Azure DevOps Engineer','DevOps Engineer',0.9),
-- Business Analyst variants
('Sr Business Analyst','Business Analyst',0.9),('Sr.Business Analyst','Business Analyst',0.9),('Lead Business Analyst','Business Analyst',0.9),('IT Business Analyst','Business Analyst',0.9),('Technical Business Analyst','Business Analyst',0.9),('Business Data Analyst','Business Analyst',0.9),('Healthcare Business Analyst','Business Analyst',0.9),('Salesforce Business Analyst','Business Analyst',0.9),('Senior Business Systems Analyst','Business Analyst',0.9),('Sr Business Systems Analyst','Business Analyst',0.9),('Business Analyst II','Business Analyst',0.9),('Business Process Analyst','Business Analyst',0.9),('Business Analyst/Scrum Master','Business Analyst',0.7),('Guidewire Business Analyst','Business Analyst',0.7),('Sr. Guidewire Business Analyst','Business Analyst',0.7),('Sr. Business Data Analyst','Business Analyst',0.9),('ServiceNow Business Analyst','Business Analyst',0.7),('SAP Business Analyst','Business Analyst',0.7),('Sr. Salesforce Business Analyst','Business Analyst',0.7),('Business Intelligence Analyst','Business Analyst',0.7),('Senior Business System Analyst','Business Analyst',0.9),('HRIS Analyst','Business Analyst',0.7),('EDI Analyst','Business Analyst',0.7),
-- Project Manager variants
('Senior IT Project Manager','Project Manager',0.9),('Sr. Program Manager','Project Manager',0.9),('Sr Project Manager','Project Manager',0.9),('Sr. IT Project Manager','Project Manager',0.9),('Scrum Master/Project Manager','Project Manager',0.7),('Project Manager/Scrum Master','Project Manager',0.7),('Project Coordinator','Project Manager',0.7),('Engineering Project Manager','Project Manager',0.9),('Construction Project Manager','Project Manager',0.9),('SAP Project Manager','Project Manager',0.9),('Agile Project Manager','Project Manager',0.9),('Senior Technical Project Manager','Project Manager',0.9),('Sr. Technical Project Manager','Project Manager',0.9),('Project Manager II','Project Manager',0.9),('Senior Technical Program Manager','Project Manager',0.9),('Sr. Technical Program Manager','Project Manager',0.9),('Lead Project Manager','Project Manager',0.9),('IT Program Manager','Project Manager',0.9),('IT Project Coordinator','Project Manager',0.7),('SAP Program Manager','Project Manager',0.9),('Program/Project Manager','Project Manager',0.9),('Project Manager / Scrum Master','Project Manager',0.7),('Scrum Master / Project Manager','Project Manager',0.7),('Assistant Project Manager','Project Manager',0.7),('Infrastructure Project Manager','Project Manager',0.9),('Program Director','Project Manager',0.9),('Associate Project Manager','Project Manager',0.7),('Project Management Consultant','Project Manager',0.7),
-- QA variants
('Senior QA Engineer','QA Automation Engineer',0.9),('Senior QA Analyst','QA Automation Engineer',0.9),('Senior QA Automation Engineer','QA Automation Engineer',0.9),('Sr. QA Analyst','QA Automation Engineer',0.9),('Sr. QA Automation Engineer','QA Automation Engineer',0.9),('Sr QA Engineer','QA Automation Engineer',0.9),('Sr QA Analyst','QA Automation Engineer',0.9),('QA Manager','QA Automation Engineer',0.7),('Quality Analyst','QA Automation Engineer',0.9),('Quality Assurance Specialist','QA Automation Engineer',0.9),('Quality Assurance Lead','QA Automation Engineer',0.9),('QA Automation Lead','QA Automation Engineer',0.9),('Lead QA Engineer','QA Automation Engineer',0.9),('QA Test Engineer','QA Automation Engineer',0.9),('QA Test Lead','QA Automation Engineer',0.9),('Software QA Tester','QA Automation Engineer',0.9),('Software QA Analyst','QA Automation Engineer',0.9),('Senior Quality Assurance Engineer','QA Automation Engineer',0.9),('Senior Quality Assurance Analyst','QA Automation Engineer',0.9),('Automation Test Engineer','QA Automation Engineer',0.9),('Senior Test Engineer','QA Automation Engineer',0.9),('Performance Test Engineer','QA Automation Engineer',0.9),('Performance Test Lead','QA Automation Engineer',0.9),('Performance Tester','QA Automation Engineer',0.9),('Test Analyst','QA Automation Engineer',0.7),('Test Manager','QA Automation Engineer',0.7),('Senior Automation Engineer','QA Automation Engineer',0.9),('Sr. Automation Engineer','QA Automation Engineer',0.9),('Software Tester','QA Automation Engineer',0.9),('Sr. SDET','QA Automation Engineer',0.9),('Technical Test Lead','QA Automation Engineer',0.9),('QA Automation Engineer/SDET','QA Automation Engineer',0.9),('ETL Tester','QA Automation Engineer',0.7),('ETL QA Tester','QA Automation Engineer',0.7),('Sr. Test Engineer','QA Automation Engineer',0.9),('Performance Engineer','QA Automation Engineer',0.7),('Quality Assurance Inspector','QA Automation Engineer',0.7),('Senior Software Test Engineer','QA Automation Engineer',0.9),('Sr. Quality Engineer','QA Automation Engineer',0.9),('Senior Quality Engineer','QA Automation Engineer',0.9),
-- Consultant variants
('Principal Consultant','Consultant',0.9),('Lead Consultant','Consultant',0.9),('Sr. Consultant','Consultant',0.9),('Sr Consultant','Consultant',0.9),('Technical Consultant','Consultant',0.9),('Associate Consultant','Consultant',0.9),('Senior Technical Consultant','Consultant',0.9),('Functional Consultant','Consultant',0.9),('Managing Consultant','Consultant',0.9),('Senior Principal Consultant','Consultant',0.9),('Implementation Consultant','Consultant',0.9),('Management Consultant','Consultant',0.9),('Technology Consultant','Consultant',0.9),('Assistant Consultant','Consultant',0.9),('IAM Consultant','Consultant',0.7),('Workday Consultant','Consultant',0.7),('Workday HCM Consultant','Consultant',0.7),('Sr. Workday Consultant','Consultant',0.7),('Business Consultant','Consultant',0.9),('Freelance Consultant','Consultant',0.7),('Senior Associate Consultant','Consultant',0.9),('Associate Director','Consultant',0.7),('Information Technology Consultant','Consultant',0.9),('Lead Workday Consultant','Consultant',0.7),('Sr. Kronos Consultant','Consultant',0.7),
-- Network Engineer variants
('Network Architect','Network Engineer',0.9),('Sr Network Engineer','Network Engineer',0.9),('Sr Network Security Engineer','Network Engineer',0.9),('Lead Network Engineer','Network Engineer',0.9),('Network Engineer II','Network Engineer',0.9),('Network Engineer III','Network Engineer',0.9),('Network Analyst','Network Engineer',0.7),('Network Consultant','Network Engineer',0.7),('Network Specialist','Network Engineer',0.7),('Network Support Engineer','Network Engineer',0.9),('NOC Engineer','Network Engineer',0.7),('NOC Technician','Network Engineer',0.7),('Network Manager','Network Engineer',0.7),('Voice Engineer','Network Engineer',0.7),
-- Salesforce variants
('Salesforce Consultant','Salesforce Developer',0.9),('Salesforce Architect','Salesforce Developer',0.9),('Salesforce Admin/Developer','Salesforce Developer',0.9),('Salesforce Developer/Admin','Salesforce Developer',0.9),('Salesforce Developer/Administrator','Salesforce Developer',0.9),('Salesforce Lightning Developer','Salesforce Developer',0.9),('Sr. Salesforce Lightning Developer','Salesforce Developer',0.9),('Lead Salesforce Developer','Salesforce Developer',0.9),('Sr Salesforce Developer','Salesforce Developer',0.9),('SFDC Developer','Salesforce Developer',0.9),('Salesforce Marketing Cloud Developer','Salesforce Developer',0.9),('Sr. Salesforce Developer/Admin','Salesforce Developer',0.9),
-- ServiceNow variants
('ServiceNow Developer/Admin','ServiceNow Developer',0.9),('ServiceNow Admin/Developer','ServiceNow Developer',0.9),('Service Now Developer','ServiceNow Developer',0.9),('Senior ServiceNow Developer','ServiceNow Developer',0.9),('Sr. ServiceNow Developer','ServiceNow Developer',0.9),
-- Data Engineer variants
('AWS Data Engineer','Data Engineer',0.9),('Sr. Big Data Engineer','Data Engineer',0.9),('Lead Data Engineer','Data Engineer',0.9),('GCP Data Engineer','Data Engineer',0.9),('Sr. AWS Data Engineer','Data Engineer',0.9),('Sr. GCP Data Engineer','Data Engineer',0.9),('Cloud Data Engineer','Data Engineer',0.9),('Sr. Azure Data Engineer','Data Engineer',0.9),('Hadoop Developer','Data Engineer',0.7),('Hadoop Administrator','Data Engineer',0.7),('Sr Data Engineer','Data Engineer',0.9),
-- Data Scientist variants
('Lead Data Scientist','Data Scientist',0.9),('Principal Data Scientist','Data Scientist',0.9),('Data Science Intern','Data Scientist',0.7),('Data Scientist Intern','Data Scientist',0.7),
-- Data Analyst variants
('Sr Data Analyst','Data Analyst',0.9),('Lead Data Analyst','Data Analyst',0.9),('Data Analyst Intern','Data Analyst',0.7),
-- Cloud Engineer variants
('AWS Cloud Engineer','Cloud Engineer',0.9),('Azure Cloud Engineer','Cloud Engineer',0.9),('AWS Solutions Architect','Cloud Engineer',0.9),('AWS Solution Architect','Cloud Engineer',0.9),('AWS Architect','Cloud Engineer',0.9),('Azure Architect','Cloud Engineer',0.9),('Cloud Solution Architect','Cloud Engineer',0.9),('Cloud Solutions Architect','Cloud Engineer',0.9),('AWS Cloud Architect','Cloud Engineer',0.9),('Cloud Security Engineer','Cloud Engineer',0.9),('Cloud Security Architect','Cloud Engineer',0.9),('Senior Cloud Engineer','Cloud Engineer',0.9),('Microsoft 365 Engineer','Cloud Engineer',0.7),
-- Security Engineer variants
('Cyber Security Analyst','Security Engineer',0.9),('Cyber Security Engineer','Security Engineer',0.9),('Information Security Analyst','Security Engineer',0.9),('Senior Cyber Security Engineer','Security Engineer',0.9),('IT Security Analyst','Security Engineer',0.9),('SOC Analyst','Security Engineer',0.7),('Senior Security Engineer','Security Engineer',0.9),('Sr. Security Engineer','Security Engineer',0.9),('Sr. Cyber Security Engineer','Security Engineer',0.9),('Security Officer','Security Engineer',0.7),('IAM Engineer','Security Engineer',0.7),('Sr. IAM Engineer','Security Engineer',0.7),('IT Auditor','Security Engineer',0.7),
-- Solution Architect variants
('Solutions Architect','Solution Architect',0.9),('Senior Solutions Architect','Solution Architect',0.9),('Senior Solution Architect','Solution Architect',0.9),('Sr. Solutions Architect','Solution Architect',0.9),('Application Architect','Solution Architect',0.9),('Infrastructure Architect','Solution Architect',0.9),('Lead Architect','Solution Architect',0.9),('Principal Architect','Solution Architect',0.9),('Technology Architect','Solution Architect',0.9),('Senior Technical Architect','Solution Architect',0.9),('Systems Architect','Solution Architect',0.9),('Integration Architect','Solution Architect',0.9),('System Architect','Solution Architect',0.9),('Data Architect','Solution Architect',0.7),('Senior Data Architect','Solution Architect',0.7),('Enterprise Data Architect','Solution Architect',0.7),('Big Data Architect','Solution Architect',0.7),('Business Architect','Solution Architect',0.7),
-- Technical Lead variants
('Technology Lead','Technical Lead',0.9),('Team Lead','Technical Lead',0.9),('Project Lead','Technical Lead',0.9),('Senior Technical Lead','Technical Lead',0.9),('Team Leader','Technical Lead',0.9),('Module Lead','Technical Lead',0.7),('Lead Technician','Technical Lead',0.7),('Technical Specialist','Technical Lead',0.7),('Technology Specialist','Technical Lead',0.7),('Senior Technical Specialist','Technical Lead',0.7),('Technical Director','Technical Lead',0.7),
-- IT Support variants
('IT Support','IT Support Specialist',0.9),('IT Help Desk','IT Support Specialist',0.9),('IT Help Desk Technician','IT Support Specialist',0.9),('IT Help Desk Support','IT Support Specialist',0.9),('IT Help Desk Analyst','IT Support Specialist',0.9),('IT Help Desk Specialist','IT Support Specialist',0.9),('IT Helpdesk Technician','IT Support Specialist',0.9),('IT Helpdesk Support','IT Support Specialist',0.9),('IT Field Technician','IT Support Specialist',0.9),('Desktop Engineer','IT Support Specialist',0.9),('Desktop Technician','IT Support Specialist',0.9),('Deskside Support Technician','IT Support Specialist',0.9),('Desktop Support Technician II','IT Support Specialist',0.9),('Help Desk Specialist','IT Support Specialist',0.9),('Help Desk Support Specialist','IT Support Specialist',0.9),('Help Desk Support Technician','IT Support Specialist',0.9),('Help Desk Manager','IT Support Specialist',0.7),('Helpdesk Technician','IT Support Specialist',0.9),('Helpdesk Analyst','IT Support Specialist',0.9),('Helpdesk Support','IT Support Specialist',0.9),('Computer Technician','IT Support Specialist',0.9),('Computer Support Specialist','IT Support Specialist',0.9),('Computer Support Technician','IT Support Specialist',0.9),('Computer Repair Technician','IT Support Specialist',0.9),('Tech Support','IT Support Specialist',0.9),('IT Technical Support','IT Support Specialist',0.9),('Support Engineer','IT Support Specialist',0.9),('Support Analyst','IT Support Specialist',0.7),('Support Specialist','IT Support Specialist',0.7),('Support Technician','IT Support Specialist',0.9),('Technical Support Advisor','IT Support Specialist',0.9),('Technical Support Agent','IT Support Specialist',0.9),('Technical Support Manager','IT Support Specialist',0.7),('Senior Technical Support Specialist','IT Support Specialist',0.9),('Senior Technical Support Engineer','IT Support Specialist',0.9),('IT Desktop Support','IT Support Specialist',0.9),('IT Support Engineer','IT Support Specialist',0.9),('Application Support Analyst','IT Support Specialist',0.7),('Application Support Engineer','IT Support Specialist',0.7),('Application Support Specialist','IT Support Specialist',0.7),('Production Support Analyst','IT Support Specialist',0.7),('Information Technology Support Specialist','IT Support Specialist',0.9),('Information Technology Technician','IT Support Specialist',0.9),('Information Systems Technician','IT Support Specialist',0.9),('Computer Operator','IT Support Specialist',0.7),('IT Service Desk Analyst','IT Support Specialist',0.9),('IT Service Desk Technician','IT Support Specialist',0.9),('IT Helpdesk Support','IT Support Specialist',0.9),('IT Help Desk Support','IT Support Specialist',0.9),('Senior IT Specialist','IT Support Specialist',0.9),
-- System Administrator variants
('Linux System Administrator','System Administrator',0.9),('Linux Systems Administrator','System Administrator',0.9),('Linux Systems Engineer','System Administrator',0.9),('Linux System Engineer','System Administrator',0.9),('Linux Engineer','System Administrator',0.9),('Senior Systems Administrator','System Administrator',0.9),('Senior System Administrator','System Administrator',0.9),('Sr. Systems Administrator','System Administrator',0.9),('IT Systems Administrator','System Administrator',0.9),('IT Administrator','System Administrator',0.9),('Systems Administrator II','System Administrator',0.9),('Windows System Administrator','System Administrator',0.9),('Unix Administrator','System Administrator',0.9),('Unix System Administrator','System Administrator',0.9),('SCCM Administrator','System Administrator',0.7),('Middleware Administrator','System Administrator',0.7),('VMware Engineer','System Administrator',0.7),('Senior Network Administrator','System Administrator',0.9),
-- Systems Engineer variants
('Senior System Engineer','Systems Engineer',0.9),('IT Systems Engineer','Systems Engineer',0.9),('Systems Engineer II','Systems Engineer',0.9),('Lead Systems Engineer','Systems Engineer',0.9),('Principal Systems Engineer','Systems Engineer',0.9),('Infrastructure Engineer','Systems Engineer',0.9),('Senior Infrastructure Engineer','Systems Engineer',0.9),('Server Engineer','Systems Engineer',0.7),('IT Engineer','Systems Engineer',0.7),
-- Scrum Master variants
('Sr Scrum Master','Scrum Master',0.9),('SAFe Scrum Master','Scrum Master',0.9),('Agile Coach','Scrum Master',0.7),('Enterprise Agile Coach','Scrum Master',0.7),('Scrum Master/Agile Coach','Scrum Master',0.9),
-- UI Developer variants
('Front-End Developer','UI Developer',0.9),('Front-end Developer','UI Developer',0.9),('Front End Web Developer','UI Developer',0.9),('Senior Front End Developer','UI Developer',0.9),('Senior Frontend Developer','UI Developer',0.9),('Sr. Front End Developer','UI Developer',0.9),('Front End/UI Developer','UI Developer',0.9),('UX/UI Designer','UI Developer',0.7),('UI/UX Designer','UI Developer',0.7),('UX Designer','UI Developer',0.7),('Product Designer','UI Developer',0.7),('Graphic Designer','UI Developer',0.7),('Sr UI Developer','UI Developer',0.9),('Instructional Designer','UI Developer',0.5),('Front-end Developer','UI Developer',0.9),('Designer','UI Developer',0.5),('Senior Designer','UI Developer',0.5),
-- React Developer variants
('Sr. React Developer','React Developer',0.9),('React JS Developer','React Developer',0.9),('Sr. React JS Developer','React Developer',0.9),
-- Angular Developer variants
('Sr. Angular Developer','Angular Developer',0.9),
-- Python Developer variants
('Sr Python Developer','Python Developer',0.9),('Lead Python Developer','Python Developer',0.9),
-- Android Developer variants
('Sr. Android Developer','Android Developer',0.9),('Senior iOS Developer','Android Developer',0.7),('Sr. iOS Developer','Android Developer',0.7),
-- Database Administrator variants
('Oracle Database Administrator','Database Administrator',0.9),('Senior Oracle Database Administrator','Database Administrator',0.9),('Senior Oracle DBA','Database Administrator',0.9),('Sr. Oracle DBA','Database Administrator',0.9),('Oracle PL/SQL Developer','Database Administrator',0.7),('Sr. Oracle PL/SQL Developer','Database Administrator',0.7),('Oracle Developer','Database Administrator',0.7),('SQL DBA','Database Administrator',0.9),('SQL Database Administrator','Database Administrator',0.9),('SQL Server Database Administrator','Database Administrator',0.9),('Sr. SQL Server DBA','Database Administrator',0.9),('Sr. Database Administrator','Database Administrator',0.9),('Senior Database Engineer','Database Administrator',0.9),('Senior Database Developer','Database Administrator',0.9),('Database Developer','Database Administrator',0.9),('Database Engineer','Database Administrator',0.9),('Sr. Data Modeler','Database Administrator',0.7),('Sr. Data Architect','Database Administrator',0.7),
-- ETL Developer variants
('Sr. Informatica Developer','ETL Developer',0.9),('ETL Informatica Developer','ETL Developer',0.9),('ETL/Informatica Developer','ETL Developer',0.9),('Senior ETL Developer','ETL Developer',0.9),('SQL/ETL Developer','ETL Developer',0.9),('Talend Developer','ETL Developer',0.9),('Sr. ETL Informatica Developer','ETL Developer',0.9),
-- SAP Consultant variants
('SAP MM Consultant','SAP Consultant',0.9),('SAP ABAP Consultant','SAP Consultant',0.9),('SAP SD Functional Consultant','SAP Consultant',0.9),('SAP Basis Consultant','SAP Consultant',0.9),('SAP Basis Administrator','SAP Consultant',0.9),('Senior SAP Consultant','SAP Consultant',0.9),('Senior SAP Basis Consultant','SAP Consultant',0.9),('SAP Security Consultant','SAP Consultant',0.9),('SAP HCM Consultant','SAP Consultant',0.9),('SAP EWM Consultant','SAP Consultant',0.9),('SAP Technical Consultant','SAP Consultant',0.9),('SAP Solution Architect','SAP Consultant',0.9),('SAP Architect','SAP Consultant',0.9),('Sr. SAP FICO Consultant','SAP Consultant',0.9),('SAP FI/CO Consultant','SAP Consultant',0.9),('SAP Mm Consultant','SAP Consultant',0.9),('SAP Senior Consultant','SAP Consultant',0.9),('SAP SD Consultant','SAP Consultant',0.9),('SAP SAP Solution Architect','SAP Consultant',0.9),
-- Tableau/BI variants
('Senior BI Developer','Tableau Developer',0.9),('Sr. Power BI Developer','Tableau Developer',0.9),('Cognos Developer','Tableau Developer',0.7),('Snowflake Developer','Tableau Developer',0.7),('Sr. Snowflake Developer','Tableau Developer',0.7),('Splunk Engineer','Tableau Developer',0.7),('GIS Analyst','Tableau Developer',0.5),
-- MuleSoft variants
('Sr. MuleSoft Developer','MuleSoft Developer',0.9),
-- Pega/niche platform variants
('Guidewire Developer','Pega Developer',0.7),('SailPoint Developer','Pega Developer',0.7),
-- Product Manager variants
('Senior Product Owner','Product Manager',0.9),('Technical Product Manager','Product Manager',0.9),
-- IT Manager variants
('Director of Information Technology','IT Manager',0.9),('Director of IT','IT Manager',0.9),('Information Technology Manager','IT Manager',0.9),('IT Operations Manager','IT Manager',0.9),('Technical Manager','IT Manager',0.7),('Senior IT Manager','IT Manager',0.9),('Director of Technology','IT Manager',0.9),('IT Coordinator','IT Manager',0.7),
-- Customer Service variants
('Customer Service','Customer Service Representative',0.9),('Customer Service Rep','Customer Service Representative',0.9),('Customer Service Specialist','Customer Service Representative',0.9),('Customer Service Associate','Customer Service Representative',0.9),('Customer Care Representative','Customer Service Representative',0.9),('Customer Support Specialist','Customer Service Representative',0.9),('Customer Support','Customer Service Representative',0.9),('Customer Services Representative','Customer Service Representative',0.9),('Call Center Representative','Customer Service Representative',0.9),('CSR - Customer Service Representative','Customer Service Representative',0.9),('Customer Service Supervisor','Customer Service Representative',0.7),('Customer Service Manager','Customer Service Representative',0.7),('Cashier/Customer Service','Customer Service Representative',0.7),('Customer Success Manager','Customer Service Representative',0.7),('Patient Service Representative','Customer Service Representative',0.7),
-- Sales Representative variants
('Account Manager','Sales Representative',0.7),('Inside Sales Representative','Sales Representative',0.9),('Sales Associate','Sales Representative',0.9),('Sales Engineer','Sales Representative',0.7),('Sales Consultant','Sales Representative',0.7),('Sales Executive','Sales Representative',0.7),('Sales Specialist','Sales Representative',0.7),('Retail Sales Associate','Sales Representative',0.9),('Senior Account Executive','Sales Representative',0.9),('Senior Account Manager','Sales Representative',0.7),('Enterprise Account Executive','Sales Representative',0.9),('Account Executive','Sales Representative',0.9),('Outside Sales Representative','Sales Representative',0.9),
-- Sales Manager variants
('District Manager','Sales Manager',0.9),('Territory Sales Manager','Sales Manager',0.9),('Territory Manager','Sales Manager',0.9),('District Sales Manager','Sales Manager',0.9),('National Sales Manager','Sales Manager',0.9),('Director of Sales','Sales Manager',0.9),('Sales Director','Sales Manager',0.9),('Regional Sales Manager','Sales Manager',0.9),('Regional Manager','Sales Manager',0.7),
-- Operations Manager variants
('Senior Manager','Operations Manager',0.7),('General Manager','Operations Manager',0.7),('Director of Operations','Operations Manager',0.9),('Production Manager','Operations Manager',0.7),('Production Supervisor','Operations Manager',0.7),('Operations Supervisor','Operations Manager',0.9),('Warehouse Manager','Operations Manager',0.7),('Manufacturing Manager','Operations Manager',0.7),('Service Manager','Operations Manager',0.7),('Service Delivery Manager','Operations Manager',0.7),('Delivery Manager','Operations Manager',0.7),('Engagement Manager','Operations Manager',0.7),('MANAGER','Operations Manager',0.3),('Manager','Operations Manager',0.3),('Director','Operations Manager',0.5),('DIRECTOR','Operations Manager',0.5),('Senior Director','Operations Manager',0.7),('Executive Director','Operations Manager',0.7),('Managing Director','Operations Manager',0.7),('Supervisor','Operations Manager',0.5),('Shift Supervisor','Operations Manager',0.5),('Sr. Manager','Operations Manager',0.7),('Assistant Manager','Operations Manager',0.7),('Area Manager','Operations Manager',0.7),('Branch Manager','Operations Manager',0.7),('Facilities Manager','Operations Manager',0.7),('Associate Manager','Operations Manager',0.7),
-- HR variants
('Human Resource Manager','Human Resources Manager',0.9),('Human Resource Director','Human Resources Manager',0.9),('Director of Human Resources','Human Resources Manager',0.9),('Human Resources Generalist','Human Resources Manager',0.7),('Human Resources Coordinator','Human Resources Manager',0.7),('Human Resources Business Partner','Human Resources Manager',0.7),('Human Resources Assistant','Human Resources Manager',0.7),('HR Generalist','Human Resources Manager',0.7),('Talent Acquisition Specialist','Human Resources Manager',0.7),('Senior Recruiter','Human Resources Manager',0.7),('Senior Technical Recruiter','Human Resources Manager',0.7),('Payroll Specialist','Human Resources Manager',0.7),('Payroll Administrator','Human Resources Manager',0.7),
-- Registered Nurse variants
('Director of Nursing','Registered Nurse',0.7),('Nurse Practitioner','Registered Nurse',0.9),('Nurse Manager','Registered Nurse',0.7),('Family Nurse Practitioner','Registered Nurse',0.9),('Clinical Nurse Manager','Registered Nurse',0.7),('Licensed Vocational Nurse','Registered Nurse',0.7),('Clinical Director','Registered Nurse',0.7),('Chief Nursing Officer','Registered Nurse',0.7),('Certified Nursing Assistant','Registered Nurse',0.7),('CNA','Registered Nurse',0.7),('CNA - Certified Nursing Assistant','Registered Nurse',0.7),('LPN','Registered Nurse',0.7),('RN Case Manager','Registered Nurse',0.9),
-- Electrician variants
('Industrial Electrician','Electrician',0.9),('Maintenance Electrician','Electrician',0.9),('Electrical Technician','Electrician',0.9),('Electrical Designer','Electrician',0.7),('Electrical Design Engineer','Electrician',0.7),('Electrical Controls Engineer','Electrician',0.7),('Senior Controls Engineer','Electrician',0.7),
-- Aviation variants
('Aviation Maintenance Technician','A&P Mechanic',0.9),('Aircraft Technician','A&P Mechanic',0.9),('Aviation Structural Mechanic','Structures Mechanic',0.9),('Aircraft Structures Mechanic','Structures Mechanic',0.9),('Aircraft Structural Mechanic','Structures Mechanic',0.9),('A&P Technician','A&P Mechanic',0.9),('Mechanic','A&P Mechanic',0.7),('Aviation Electronics Technician','Avionics Technician',0.9),('Aircraft Sheet Metal Mechanic','Sheet Metal Technician',0.9),('Sheet Metal Worker','Sheet Metal Technician',0.9),('Line Service Technician','A&P Mechanic',0.7),
-- Misc role mappings
('Analyst','Systems Analyst',0.5),('Senior Analyst','Systems Analyst',0.7),('Senior IT Analyst','Systems Analyst',0.7),('IT Analyst','Systems Analyst',0.7),('Technology Analyst','Systems Analyst',0.7),('Senior Systems Analyst','Systems Analyst',0.9),('System Analyst','Systems Analyst',0.9),('Programmer Analyst','Programmer Analyst',1.0),('Senior Programmer Analyst','Programmer Analyst',0.9),('Senior Programmer','Programmer Analyst',0.7),('Programmer/Analyst','Programmer Analyst',0.9),('Senior Programmer/Analyst','Programmer Analyst',0.9),('Systems Programmer','Programmer Analyst',0.7),('Senior Systems Programmer','Programmer Analyst',0.7),
('Architect','Solution Architect',0.5),('Technician','Maintenance Technician',0.5),('TECHNICIAN','Maintenance Technician',0.5),('technician','Maintenance Technician',0.5),('Tech','Maintenance Technician',0.5),
('Contractor','Consultant',0.5),('Independent Contractor','Consultant',0.5),('INDEPENDENT CONTRACTOR','Consultant',0.5),('Freelance','Consultant',0.5),('Freelancer','Consultant',0.5),('Self Employed','Consultant',0.3),('Self-Employed','Consultant',0.3),('Self-employed','Consultant',0.3),('SELF EMPLOYED','Consultant',0.3),
('Owner','Consultant',0.3),('OWNER','Consultant',0.3),('Owner/Operator','Consultant',0.3),('Co-Owner','Consultant',0.3),('Business Owner','Consultant',0.3),('Co-Founder','Consultant',0.3),('Founder','Consultant',0.3),('President','Consultant',0.3),('CEO','Consultant',0.3),('Chief Executive Officer','Consultant',0.3),('CTO','Consultant',0.3),('Chief Technology Officer','Consultant',0.3),('Chief Operating Officer','Consultant',0.3),('Chief Information Officer','Consultant',0.3),('Vice President','Consultant',0.3),('VP','Consultant',0.3),('Partner','Consultant',0.3),('Managing Partner','Consultant',0.3),
('PHP Developer','Web Developer',0.9),('Sr. PHP Developer','Web Developer',0.9),('AEM Developer','Web Developer',0.9),('Senior AEM Developer','Web Developer',0.9),('Sr. AEM Developer','Web Developer',0.9),('Freelance Web Developer','Web Developer',0.9),
('Structural Engineer','Mechanical Engineer',0.7),('Civil Engineer','Mechanical Engineer',0.7),('Hardware Engineer','Mechanical Engineer',0.7),('RF Engineer','Mechanical Engineer',0.7),('R&D Engineer','Mechanical Engineer',0.7),('Senior Mechanical Engineer','Mechanical Engineer',0.9),('Senior Mechanical Design Engineer','Mechanical Engineer',0.9),('Senior Manufacturing Engineer','Mechanical Engineer',0.9),('Sr. Manufacturing Engineer','Mechanical Engineer',0.9),('Lead Mechanical Engineer','Mechanical Engineer',0.9),('Mechanical Designer','Mechanical Engineer',0.7),('Senior Design Engineer','Design Engineer',0.9),('Product Engineer','Mechanical Engineer',0.7),('Applications Engineer','Mechanical Engineer',0.7),('Consulting Engineer','Mechanical Engineer',0.7),
('Maintenance Engineer','Maintenance Technician',0.9),('Lead Maintenance Technician','Maintenance Technician',0.9),('Industrial Maintenance Technician','Maintenance Technician',0.9),('Industrial Maintenance Mechanic','Maintenance Technician',0.9),('Maintenance Mechanic','Maintenance Technician',0.9),('Maintenance Manager','Maintenance Technician',0.7),('Manufacturing Technician','Maintenance Technician',0.7),('Engineering Technician','Maintenance Technician',0.7),('Repair Technician','Maintenance Technician',0.7),('Cable Technician','Maintenance Technician',0.7),('Installation Technician','Maintenance Technician',0.7),('Process Technician','Maintenance Technician',0.7),('Quality Technician','Maintenance Technician',0.7),('Automotive Technician','Maintenance Technician',0.7),('Maintenance Technician II','Maintenance Technician',0.9),('Lead Maintenance Technician','Maintenance Technician',0.9),('Senior Technician','Maintenance Technician',0.7),('Shop Technician','Maintenance Technician',0.7),
('HVAC Service Technician','HVAC Technician',0.9),('HVAC or HVAC/R Technician','HVAC Technician',0.9),
('Administrative Assistant','Administrative Assistant',1.0),('Receptionist','Administrative Assistant',0.7),('Front Desk Receptionist','Administrative Assistant',0.7),('Office Assistant','Administrative Assistant',0.7),('Office Manager','Administrative Assistant',0.7),('Executive Assistant','Administrative Assistant',0.9),('Data Entry','Administrative Assistant',0.7),('Data Entry Clerk','Administrative Assistant',0.7),
('Accounting Manager','Accountant',0.9),('Tax Accountant','Accountant',0.9),('Tax Manager','Accountant',0.9),('Controller','Accountant',0.7),('Corporate Controller','Accountant',0.9),('CFO','Accountant',0.7),('Chief Financial Officer','Accountant',0.7),('Financial Advisor','Accountant',0.7),('Finance Manager','Accountant',0.7),
('Welder','Aircraft Welder',0.7),('Welder/Fabricator','Aircraft Welder',0.7),('Machinist','Machine Operator',0.9),('Assembler','Machine Operator',0.7),('Assembly Technician','Machine Operator',0.7),('Forklift Operator','Machine Operator',0.7),
('Site Reliability Engineer','Site Reliability Engineer',1.0),('Senior Site Reliability Engineer','Site Reliability Engineer',0.9),
('Litigation Paralegal','Paralegal',0.9),
('Surgical Technologist','Medical Technologist',0.7),('Certified Surgical Technologist','Medical Technologist',0.7),('Radiologic Technologist','Medical Technologist',0.7),('MRI Technologist','Medical Technologist',0.7),('Ultrasound Technologist','Medical Technologist',0.7),('Medical Laboratory Technician','Medical Technologist',0.9),('Medical Laboratory Technologist','Medical Technologist',0.9),('Medical Assistant','Medical Technologist',0.7),
('Clinical Pharmacist','Pharmacy Technician',0.7),('Staff Pharmacist','Pharmacy Technician',0.7),('Certified Pharmacy Technician','Pharmacy Technician',0.9),('Pharmacy Manager','Pharmacy Technician',0.7),
('Lab Technician','Research Assistant',0.7),('Laboratory Technician','Research Assistant',0.7),('Lab Assistant','Research Assistant',0.7),('Graduate Teaching Assistant','Research Assistant',0.7),('Graduate Assistant','Research Assistant',0.7),('Teaching Assistant','Research Assistant',0.7),('Research Associate','Research Assistant',0.9),
('Warehouse Associate','Warehouse Associate',1.0),('Material Handler','Warehouse Associate',0.7),('Package Handler','Warehouse Associate',0.7),('Foreman','Warehouse Associate',0.7),('Laborer','Warehouse Associate',0.7),('General Laborer','Warehouse Associate',0.7),('Fulfillment Associate','Warehouse Associate',0.7),
('Delivery Driver','Warehouse Associate',0.5),('Driver','Warehouse Associate',0.5),('Truck Driver','Warehouse Associate',0.5),
('Cashier','Customer Service Representative',0.5),
('Intern','Research Assistant',0.3),('Internship','Research Assistant',0.3),('Student','Research Assistant',0.3),('Volunteer','Research Assistant',0.3),('VOLUNTEER','Research Assistant',0.3),('Member','Research Assistant',0.3),('Associate','Research Assistant',0.3),('Senior Associate','Research Assistant',0.3),('Principal','Research Assistant',0.3),
('Realtor','Sales Representative',0.5),('Marketing Manager','Sales Manager',0.7),('Director of Marketing','Sales Manager',0.7),('Digital Marketing Specialist','Sales Manager',0.7),('Digital Marketing Manager','Sales Manager',0.7),('Director of Business Development','Sales Manager',0.7),('Business Development','Sales Manager',0.7),
('Compliance Analyst','Financial Analyst',0.7),('Operations Analyst','Financial Analyst',0.7),('Supply Chain Analyst','Financial Analyst',0.7),
('Social Worker','Registered Nurse',0.5),('Occupational Therapist','Physical Therapist',0.9),('Caregiver','Registered Nurse',0.5),('Case Manager','Registered Nurse',0.7),
('Cook','Warehouse Associate',0.3),('Line Cook','Warehouse Associate',0.3),('Barista','Warehouse Associate',0.3),('Bartender','Warehouse Associate',0.3),('Server','Warehouse Associate',0.3),('Crew Member','Warehouse Associate',0.3),('Team Member','Warehouse Associate',0.3),
('Teacher','Research Assistant',0.5),('Substitute Teacher','Research Assistant',0.5),('Adjunct Professor','Research Assistant',0.5),('Instructor','Research Assistant',0.5),('Tutor','Research Assistant',0.5),
('Security Guard','Security Engineer',0.3),
('Estimator','Mechanical Engineer',0.5),('Construction Manager','Operations Manager',0.7),('Property Manager','Operations Manager',0.7),
('developer','Software Engineer',0.7),('MANAGER','Operations Manager',0.3),
('Automation Architect','Automation Engineer',0.9),
('Guidewire Business Analyst','Business Analyst',0.7),
('Sr. Guidewire Business Analyst','Business Analyst',0.7),
('IT Help Desk','IT Support Specialist',0.9),
('Service Desk Manager','IT Support Specialist',0.7),('Service Desk Specialist','IT Support Specialist',0.9),
('Desktop Support Analyst','IT Support Specialist',0.9),('Desktop Support Specialist','IT Support Specialist',0.9),('Desktop Support Engineer','IT Support Specialist',0.9),
('Technical Support','IT Support Specialist',0.9),('Technical Support Representative','IT Support Specialist',0.9),('Technical Support Analyst','IT Support Specialist',0.9),('Technical Support Engineer','IT Support Specialist',0.9),('Technical Support Specialist','IT Support Specialist',0.9),
('Data Center Technician','Data Center Technician',1.0),('Datacenter Technician','Data Center Technician',0.9),
('Pharmacist','Pharmacy Technician',0.9),
('Audio Visual Technician','Maintenance Technician',0.7),('Test Technician','Maintenance Technician',0.7),
('Procurement Specialist','Supply Chain Manager',0.7),('Purchasing Manager','Supply Chain Manager',0.9),('Senior Buyer','Supply Chain Manager',0.7),('Buyer','Supply Chain Manager',0.7),('Logistics Coordinator','Supply Chain Manager',0.7),
('Quality Manager','Quality Manager',1.0),('Quality Inspector','Quality Manager',0.9),('Director of Quality','Quality Manager',0.9),
('Electronics Technician','Electronics Technician',1.0),
('EHS Manager','Operations Manager',0.7),('Plant Manager','Operations Manager',0.7),('Production Planner','Operations Manager',0.7),
('Document Control Specialist','Administrative Assistant',0.7),('Procurement Specialist','Administrative Assistant',0.7),
('Accounts Receivable Specialist','Accountant',0.7),
('Sr. Technical Program Manager','Project Manager',0.9),
('Unemployed','Consultant',0.1);

-- ============================================================
-- Part 2: Apply the mapping
-- Run this AFTER Part 1 completes
-- ============================================================

UPDATE cblaero_app.candidates c
SET deduced_roles = jsonb_build_array(m.role_name),
    role_deduction_metadata = jsonb_build_object('source','heuristic','confidence',m.confidence,'rawJobTitle',c.job_title,'deducedAt',now()::text),
    ingestion_state = 'active', updated_at = now()
FROM title_to_role m
WHERE c.tenant_id = 'cbl-aero' AND c.deduced_roles = '[]'::jsonb AND c.ingestion_state != 'merged'
  AND lower(trim(c.job_title)) = lower(m.title);

-- Check results
SELECT count(*) as matched FROM cblaero_app.candidates WHERE deduced_roles != '[]'::jsonb;
SELECT count(*) as remaining FROM cblaero_app.candidates WHERE deduced_roles = '[]'::jsonb AND ingestion_state != 'merged';

DROP TABLE title_to_role;
